---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "anyas-waku-waku"

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "anya_production"
            - name: POSTGRES_USER
              value: "anya"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anya-math-deployment
spec:
  replicas: 2 # Run 2 pods for high availability
  selector:
    matchLabels:
      app: anya-math
  template:
    metadata:
      labels:
        app: anya-math
    spec:
      containers:
        - name: anya-math
          image: anya-math:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2300
          env:
            - name: HANAMI_ENV
              value: "production"
            - name: PORT
              value: "2300"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: anya-math-service
spec:
  type: NodePort
  selector:
    app: anya-math
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2300
